# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/null/college/ProgParalela/T1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/null/college/ProgParalela/T1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/null/college/ProgParalela/T1/CMakeFiles /home/null/college/ProgParalela/T1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/null/college/ProgParalela/T1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named JoseCarlos_RGM42426_AGMseq

# Build rule for target.
JoseCarlos_RGM42426_AGMseq: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JoseCarlos_RGM42426_AGMseq
.PHONY : JoseCarlos_RGM42426_AGMseq

# fast build rule for target.
JoseCarlos_RGM42426_AGMseq/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JoseCarlos_RGM42426_AGMseq.dir/build.make CMakeFiles/JoseCarlos_RGM42426_AGMseq.dir/build
.PHONY : JoseCarlos_RGM42426_AGMseq/fast

#=============================================================================
# Target rules for targets named JoseCarlos_RGM42426_AGMpar

# Build rule for target.
JoseCarlos_RGM42426_AGMpar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JoseCarlos_RGM42426_AGMpar
.PHONY : JoseCarlos_RGM42426_AGMpar

# fast build rule for target.
JoseCarlos_RGM42426_AGMpar/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JoseCarlos_RGM42426_AGMpar.dir/build.make CMakeFiles/JoseCarlos_RGM42426_AGMpar.dir/build
.PHONY : JoseCarlos_RGM42426_AGMpar/fast

JoseCarlos_RGM42426_AGMpar.o: JoseCarlos_RGM42426_AGMpar.c.o
.PHONY : JoseCarlos_RGM42426_AGMpar.o

# target to build an object file
JoseCarlos_RGM42426_AGMpar.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JoseCarlos_RGM42426_AGMpar.dir/build.make CMakeFiles/JoseCarlos_RGM42426_AGMpar.dir/JoseCarlos_RGM42426_AGMpar.c.o
.PHONY : JoseCarlos_RGM42426_AGMpar.c.o

JoseCarlos_RGM42426_AGMpar.i: JoseCarlos_RGM42426_AGMpar.c.i
.PHONY : JoseCarlos_RGM42426_AGMpar.i

# target to preprocess a source file
JoseCarlos_RGM42426_AGMpar.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JoseCarlos_RGM42426_AGMpar.dir/build.make CMakeFiles/JoseCarlos_RGM42426_AGMpar.dir/JoseCarlos_RGM42426_AGMpar.c.i
.PHONY : JoseCarlos_RGM42426_AGMpar.c.i

JoseCarlos_RGM42426_AGMpar.s: JoseCarlos_RGM42426_AGMpar.c.s
.PHONY : JoseCarlos_RGM42426_AGMpar.s

# target to generate assembly for a file
JoseCarlos_RGM42426_AGMpar.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JoseCarlos_RGM42426_AGMpar.dir/build.make CMakeFiles/JoseCarlos_RGM42426_AGMpar.dir/JoseCarlos_RGM42426_AGMpar.c.s
.PHONY : JoseCarlos_RGM42426_AGMpar.c.s

JoseCarlos_RGM42426_AGMseq.o: JoseCarlos_RGM42426_AGMseq.c.o
.PHONY : JoseCarlos_RGM42426_AGMseq.o

# target to build an object file
JoseCarlos_RGM42426_AGMseq.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JoseCarlos_RGM42426_AGMseq.dir/build.make CMakeFiles/JoseCarlos_RGM42426_AGMseq.dir/JoseCarlos_RGM42426_AGMseq.c.o
.PHONY : JoseCarlos_RGM42426_AGMseq.c.o

JoseCarlos_RGM42426_AGMseq.i: JoseCarlos_RGM42426_AGMseq.c.i
.PHONY : JoseCarlos_RGM42426_AGMseq.i

# target to preprocess a source file
JoseCarlos_RGM42426_AGMseq.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JoseCarlos_RGM42426_AGMseq.dir/build.make CMakeFiles/JoseCarlos_RGM42426_AGMseq.dir/JoseCarlos_RGM42426_AGMseq.c.i
.PHONY : JoseCarlos_RGM42426_AGMseq.c.i

JoseCarlos_RGM42426_AGMseq.s: JoseCarlos_RGM42426_AGMseq.c.s
.PHONY : JoseCarlos_RGM42426_AGMseq.s

# target to generate assembly for a file
JoseCarlos_RGM42426_AGMseq.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JoseCarlos_RGM42426_AGMseq.dir/build.make CMakeFiles/JoseCarlos_RGM42426_AGMseq.dir/JoseCarlos_RGM42426_AGMseq.c.s
.PHONY : JoseCarlos_RGM42426_AGMseq.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... JoseCarlos_RGM42426_AGMpar"
	@echo "... JoseCarlos_RGM42426_AGMseq"
	@echo "... JoseCarlos_RGM42426_AGMpar.o"
	@echo "... JoseCarlos_RGM42426_AGMpar.i"
	@echo "... JoseCarlos_RGM42426_AGMpar.s"
	@echo "... JoseCarlos_RGM42426_AGMseq.o"
	@echo "... JoseCarlos_RGM42426_AGMseq.i"
	@echo "... JoseCarlos_RGM42426_AGMseq.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

